services:
  db:
    build: ./db
    image: grc_db
    container_name: grc_db
    ports:
      - 3306:3306
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: ./server
    image: grc_server
    container_name: grc_server
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
  client:
    build: ./client
    image: grc_client
    container_name: grc_client
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
